# Exported from Render on 2024-10-30T19:28:54Z
services:
- type: web
  name: task-management-api
  runtime: static
  repo: https://github.com/zee-ham-su/task-management-api
  envVars:
  - key: CACHE_MAX
    sync: false
  - key: CACHE_TTL
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: PORT
    sync: false
  - key: MONGODB_URI
    sync: false
  buildCommand: npm install && npm run build
  staticPublishPath: dist
version: "1"
